import {
    FaCss3Alt,
    FaJava,
    FaTerminal,
    FaCube,
    FaNetworkWired,
    FaProjectDiagram,
    FaRoute,
    FaGlobe,
    FaUserTag,
    FaEthernet,
    FaServer,
    FaEnvelope,
    FaHashtag,
    FaDatabase,
    FaWindows,
    FaCubes,
} from 'react-icons/fa';
import {
    SiHtml5,
    SiJavascript,
    SiPhp,
    SiMysql,
    SiReact,
    SiTailwindcss,
    SiPython,
    SiDocker,
    SiCplusplus,
    SiGit,
    SiLinux,
    SiArduino,
    SiWireshark,
    SiVirtualbox,
    SiCisco,
    SiGithub,
} from 'react-icons/si';

const iconesCompetences = {
    'HTML5': SiHtml5,
    'CSS3': FaCss3Alt,
    'JavaScript': SiJavascript,
    'PHP': SiPhp,
    'MySQL': SiMysql,
    'React.js': SiReact,
    'Tailwind CSS': SiTailwindcss,
    'Python': SiPython,
    'C#': FaHashtag,
    'Java': FaJava,
    'Shell': FaTerminal,
    'C++': SiCplusplus,
    'SQL': FaDatabase,
    'Docker': SiDocker,
    'Git': SiGit,
    'Linux': SiLinux,
    'Arduino': SiArduino,
    'Tinkercad': FaCube,
    'Windows': FaWindows,
    'Wireshark': SiWireshark,
    'GNS3': FaCubes,
    'Cisco Packet Tracer': SiCisco,
    'VirtualBox': SiVirtualbox,
    'GitHub': SiGithub,
    'TCP/IP': FaNetworkWired,
    'VLAN': FaProjectDiagram,
    'Routage (RIP/OSPF)': FaRoute,
    'DNS': FaGlobe,
    'LDAP': FaUserTag,
    'DHCP': FaEthernet,
    'APACHE2/NGINX': FaServer,
    'MAIL': FaEnvelope,
};

export default iconesCompetences;